name: Build

on:
  push:
    branches:
      - main
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build common
        run: npm run publish -- -k

      - name: Upload Package to GitHub Packages
        run: |
          ZIP_NAME=$(ls *.zip)
          PACKAGE_NAME=$(echo $ZIP_NAME | cut -d'@' -f1)
          VERSION=$(echo $ZIP_NAME | cut -d'@' -f2)
          REVISION=$(echo $ZIP_NAME | cut -d'@' -f3 | cut -d'.' -f1)
          
          gh release create $VERSION.$REVISION "$ZIP_NAME" -t "$PACKAGE_NAME v$VERSION.$REVISION" -n "Release $VERSION.$REVISION (Revision $REVISION)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
